# Generated by Django 4.1.1 on 2022-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('Roomno', models.IntegerField(primary_key=True, serialize=False)),
                ('RoomType', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], max_length=10)),
                ('Status', models.CharField(choices=[('C', 'CLEANED'), ('N', 'NOTCLEANED'), ('O', 'OCCUPIED')], default='C', max_length=10)),
                ('Checkin', models.DateTimeField()),
                ('Reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
