# Generated by Django 4.1.1 on 2022-10-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_alter_rooms_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Checkin',
            field=models.DateTimeField(null=True),
        ),
    ]
